language: node_js
node_js:
  - lts/*

stage:
  - github
  - heroku
  - test

jobs:
  include:
    - stage: github
      name: 'Github Deploy'
      script: yarn zip
      deploy:
        provider: releases
        api_key: $GITHUB_API_KEY
        file: "./dist/master.zip"
        overwrite: true
        file_glob: true
        on:
          branch: production
          tags: true
      after_deploy:
        - echo Notification
  
    - stage: heroku
      name: 'Heroku Deploy'
      script: yarn build
      before_deploy: yarn test
      deploy: &heroku
        provider: heroku
        api_key: $HEROKU_API_KEY
        app:
          master: davidsdevel-blog-test
          davidsdevel: davidsdevel-blog
        on:
          branch:
            - master
            - davidsdevel
    
    - stage: test
      name: "Testing deploy"
      script:
        - curl https://davidsdevel-blog-test.herokuapp.com
        - curl https://davidsdevel-blog.herokuapp.com