language: node_js
node_js: lts/*

jobs:
  include:
    stage: github
    script: yarn zip
    deploy:
      provider: releases
      api_key: $GITHUB_API_KEY
      file: "./dist/master.zip"
      overwrite: true
      file_glob: true
      on:
        branch: production
        tags: true
  
    stage: heroku
    script: yarn build
    before_deploy:
      - rm -r components
      - rm -r pages
      - rm -r lib/client
      - rm -r src
      - rm -r store
    deploy: &heroku
      provider: heroku
      api_key: $HEROKU_API_KEY
      app:
        master: davidsdevel-blog-test
        davidsdevel: davidsdevel-blog
    
    stage: test apps
    script:
      - curl https://demo.davidsdevel.tk
      - curl https://davidsdevel-test.herokuapp.com